@startuml "sd1"

[*] -down-> S1 : [a-zA-Z]
[*] -left-> S2 : _
S2 -down-> S1 : [a-zA-Z_0-9]
S1 -left-> S1 : [a-zA-Z_0-9]
S1 -left-> S6 : [^a-zA-Z_0-9]
S1 : Идентификатор
S6 : Смотреть\nпредыдущее\nсостояние

[*] -right-> S3 : "
S3 -right-> S3 : [^"]
S3 -down-> S4 : "
S4 : Строчный литерал

[*] -up-> S5 : /
S5 -up-> S7 : *
S5 : ОП /
S5 -left-> S6 : [^*=]
S5 -right-> S8 : =

S8 : ОП /=

S7 -up-> S7 : [^*]
S7 -up-> S9 : *
S9 -down-> S7 : [^/]
S9 -left-> S10 : /
S10 : Коммент


@enduml