@startuml "sd"

[*] -left-> S1 : [a-zA-Z]
[*] -left-> S43 : _
S43 -left-> S1 : [a-zA-Z]
S1 -left-> S1 : [a-zA-Z_0-9]
S1 -up-> S2 : пункт., или оператор, или вайтспейс
S2 : ИД

[*] -right-> S3 : "
S3 -right-> S3 : Любой символ кроме "
S3 -down-> S4 : "
S4 : строчный литерал

[*] -up-> S5 : /
S5 -up-> S6 : ИД|Число|WS
S6 : ОП
S5 -up-> S7 : *

S5 -right-> S26 : ИД|Число|WS
S26 : ОП
S5 -right-> S27 : =
S27 : ОП

S7 -up-> S7 : Любой символ кроме *
S7 -up-> S9 : *
S9 -down-> S7 : Любой символ кроме /
S9 -left-> S10 : /
S10 : Коммент


@enduml