@startuml "sd2"

[*] --> S12 : +
S12 --> S13 : +
S13 : ОП ++
S12 --> S14 : =
S14 : ОП +=
S12 -up-> S6 : [^+=]
S12 : ОП +

[*] --> S15 : -
S15 --> S16 : -
S16 : ОП --
S15 --> S17 : =
S17 : ОП -=
S15 -up-> S6 : [^-=]
S15 : ОП -

[*] -up-> S18 : =
S18 -up-> S6 : [^=]
S18 --> S19 : =
S19 : ОП ==
S18 : ОП =

[*] -up-> S20 : *
S20 -up-> S6 : [^*=]
S20 --> S21 : =
S21 : ОП *=
S20 : ОП *

S6 : Смотреть\nпредыдущее\nсостояние

@enduml