@startuml "sd2"

[*] --> S12 : +
S12 --> S13 : +
S13 : F: ОП ++
S12 --> S14 : =
S14 : F: ОП +=
S12 -up-> S6 : [^+=]
S12 : ОП +

[*] --> S15 : -
S15 --> S16 : -
S16 : F: ОП --
S15 --> S17 : =
S17 : F: ОП -=
S15 -up-> S6 : [^-=]
S15 : ОП -

[*] -up-> S18 : =
S18 -up-> S6 : [^=]
S18 --> S19 : =
S19 : F: ОП ==
S18 : ОП =

[*] -up-> S20 : *
S20 -up-> S6 : [^*=]
S20 --> S21 : =
S21 : F: ОП *=
S20 : ОП *

S6 : F: Смотреть\nпредыдущее\nсостояние

@enduml