@startuml "sd2"

state "S-8" as Operator
Operator : F: Введен оператор
S12 : ОП +
S13 : ОП ++
S14 : ОП +=
S15 : ОП -
S16 : ОП --
S17 : ОП -=
S18 : ОП =
S19 : ОП ==
S20 : ОП *
S21 : ОП *=

[*] --> S12 : +
S12 --> S13 : +
S13 -up-> Operator : Любой символ
S12 --> S14 : =
S14 -up-> Operator : Любой символ
S12 -up-> Operator : [^+=]

[*] --> S15 : -
S15 --> S16 : -
S16 -up-> Operator : Любой символ
S15 --> S17 : =
S17 -up-> Operator : Любой символ
S15 -up-> Operator : [^-=]

[*] -up-> S18 : =
S18 -up-> Operator : [^=]
S18 --> S19 : =
S19 -up-> Operator : Любой символ

[*] -up-> S20 : *
S20 -up-> Operator : [^*=]
S20 --> S21 : =
S21 -up-> Operator : Любой символ

@enduml