@startuml "sd3"

[*] -right-> S22 : [WS]
S22 --> S22 : [WS]
S22 : WS
S22 -up-> S6 : [^WS]

[*] -up-> S23 : <
S23 -up-> S6 : [^<=]
S23 -up-> S24 : <
S24 : ОП <<
S23 -up-> S25 : =
S25 : ОП <=
S23 : ОП <

[*] --> S26 : >
S26 -up-> S6 : [^>=]
S26 --> S27 : >
S27 : ОП >>
S26 --> S28 : =
S28 : ОП >=
S26 : ОП >

S6 : Смотреть\nпредыдущее\nсостояние

@enduml