@startuml "sd"

[*] --> S54 : 0
S54 --> S36 : 1|2-9
S54 --> S37 : x|X
S54 --> S39 : b|B

[*] --> S36 : 1|2-9
S36 --> S36 : [0-9_]
S36 --> S41 : '.'
S36 --> S55 : Оператор|WS|Punctuator
S55 : Десятичное целое

S37 --> S38 : [_(0-9|A-F|a-f)]
S38 : Шестнадцатеричное целое

S39 --> S40 : [_0-1]
S40 : Двоичное целое

S41 --> S42 : [0-9]
S42 --> S42 : [0-9_]
S42 --> S56 : Оператор|WS|Punctuator
S56 : Дробное число

[*] -up-> S44 : '
S44 -up-> S45 : Любой кроме апострофа
S45 -right-> S46 : '
S46 : Символьный литерал

[*] -up-> S47 : &
S47 -up-> S47 : &
S47 -up-> S48 : [\&]
S48 : ОП

[*] -up-> S49 : |
S49 -up-> S49 : |
S49 -up-> S50 : [\|]
S50 : ОП

[*] -left-> S51 : !
S51 -up-> S51 : !
S51 -left-> S52 : [\!]
S52 : ОП

@enduml