@startuml "sd4"

[*] -left-> S29 : 0
S29 --> S30 : 1|2-9
S29 --> S31 : x|X
S29 --> S32 : b|B
S29 --> S6 : [^0-9xXbB]
S29 : Десятичное целое

[*] --> S30 : 1|2-9
S30 --> S30 : [0-9_]
S30 --> S33 : '.'
S30 --> S6 : [^0-9_\.]
S6 : Смотреть\nпредыдущее\nсостояние
S30 : Десятичное целое

S31 --> S31 : [_0-9A-Fa-f]
S31 : Шестнадцатеричное целое
S31 --> S6 : [^_0-9A-Fa-f]

S32 --> S32 : [_0-1]
S32 : Двоичное целое
S32 --> S6 : [^_0-1]

S33 --> S34 : [0-9]
S34 --> S34 : [0-9_]
S34 --> S6 : [^0-9_]
S34 : Дробное число

@enduml