@startuml "sd4"

[*] -left-> S27 : 0
S27 --> S28 : 1|2-9
S27 --> S29 : x|X
S27 --> S30 : b|B
S27 --> S6 : [^0-9xXbB]
S27 : Десятичное целое

[*] --> S28 : 1|2-9
S28 --> S28 : [0-9_]
S28 --> S31 : '.'
S28 --> S6 : [^0-9_\.]
S6 : Смотреть\nпредыдущее\nсостояние
S28 : Десятичное целое

S29 --> S29 : [_0-9A-Fa-f]
S29 : Шестнадцатеричное целое
S29 --> S6 : [^_0-9A-Fa-f]

S30 --> S30 : [_0-1]
S30 : Двоичное целое
S30 --> S6 : [^_0-1]

S31 --> S32 : [0-9]
S32 --> S32 : [0-9_]
S32 --> S6 : [^0-9_]
S32 : Дробное число

@enduml