@startuml "sd5"

[*] -right-> S38 : &
S38 -up-> S39 : =
S38 -up-> S40 : &
S39 : ОП &=
S38 : ОП &
S40 : ОП &&
S38 -down-> S6 : [^&=]

[*] -left-> S44 : !
S44 -left-> S45 : =
S45 : ОП !=
S44 : ОП !
S44 -down-> S6 : [^=]

S6 : Смотреть\nпредыдущее\nсостояние

@enduml