@startuml "sd5"

[*] -right-> S36 : &
S36 -up-> S37 : =
S36 -up-> S38 : &
S37 : ОП &=
S36 : ОП &
S38 : ОП &&
S36 -down-> S6 : [^&=]

[*] -left-> S42 : !
S42 -left-> S43 : =
S43 : ОП !=
S42 : ОП !
S42 -down-> S6 : [^=]

S6 : Смотреть\nпредыдущее\nсостояние

@enduml