@startuml "sd6"

[*] -right-> S35 : '
S35 -up-> S47 : \\
S35 -right-> S36 : [^']
S36 -right-> S37 : '
S37 : F: Символьный литерал

[*] -up-> S41 : |
S41 -up-> S43 : |
S41 -up-> S42 : =
S42 : F: ОП |=
S43 : F: ОП ||
S41 : ОП |
S41 -left-> S6 : [^|=]

[*] --> S46 : [[]{}().,:;]
S46 : F: Разделитель,\nзнак препинания

S47 -down-> S36 : [^']
S47 -down-> S37 : '

S6 : F: Смотреть\nпредыдущее\nсостояние

@enduml