@startuml "sd6"

[*] -right-> S33 : '
S33 -right-> S34 : [^']
S34 -right-> S35 : '
S35 : Символьный литерал

[*] -up-> S39 : |
S39 -up-> S41 : |
S39 -up-> S40 : =
S40 : ОП |=
S41 : ОП ||
S39 : ОП |
S39 -left-> S6 : [^|=]

[*] --> S44 : [[]{}().,:;]
S44 : Разделитель, знак препинания

S6 : Смотреть\nпредыдущее\nсостояние

@enduml