@startuml "Построитель таблицы переходов"

[*] -up-> S1 : [0-9]
S1 --> S1 : [0-9]
S1 --> S2 : Space
S2 : F: Введено\nначальное\nсостояние
S2 -up-> S3 : -
S3 -up-> S4 : >
S4 -right-> S5 : Space
S5 --> S1 : [0-9]
S5 -right-> S11 : *
S11 -right-> S12 : Space 
S12 : F: Введены\nвсе\nклассы\nсимволов


S1 -right-> S7 : Запятая
S7 : F: Введен\nсимвольный\nкласс
S7 -left-> S1 : Пробел

S1 --> S8 : =
S8 --> S9 : >
S9 -right-> S6 : Space
S6 --> S6 : [0-9\-]
S6 --> S10 : \\r
S10 : F: Введено\nконечное\nсостояние
S10 --> [*] : EOL

@enduml 